import { ShoppingContextProvider } from "@/contexts/ShoppingContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//npx json-server -w data/product.json -p 3001       RUN FAKE DATA HERE

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <ShoppingContextProvider>
            {children}
            </ShoppingContextProvider>
        </div>
      </body>
    </html>
  );
}
